### ISSUE TITLE
Guild masters are not able to toggle the status of their guild.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#45]
RE: https://github.com/darbyjack/Guilds-Plugin/issues/36

Toggling guild status permissions break when you set ```ally-chat: false``` in the guild role's permissions. As the guild leader, it outputs 'Your role is not high enough to do that!'.

**Comment by darbyjack** [comment]
I just tested and this works fine, I wonder if I fixed it in an update and didn't realize. Feel free to re-open if it continues.

**Comment by mibby** [comment]
@darbyjack This is still broken for me as of dev 60. Same issue; with ally-chat set to false on guild-leader role permissions in the config, you can't toggle the guild status. With ally-chat enabled, you can toggle fine.

I can't re-open the ticket since I have no repo permissions. You'll need to re-open.

**Comment by mibby** [comment]
Bump.
